name: ridy
description: Driver application of Ridy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  artemis: 7.2.6-beta
  country_code_picker: ^2.0.2
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^4.2.7
  firebase_analytics: ^9.0.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  fl_chart: ^0.40.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_chat_ui: ^1.5.3
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^1.0.0
  google_maps_flutter: ^2.1.1
  gql: 0.13.1-alpha+1635149947792
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  lottie: ^1.1.0
  marquee: ^2.2.0
  meta: ^1.3.0
  package_info_plus: ^1.3.0
  sms_autofill: ^2.1.0
  url_launcher: ^6.0.17
  velocity_x: ^3.3.0
  map_launcher: ^2.1.1
  flutter_svg: 0.23.0+1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/default-user-image.png
    - images/logo.png
    - images/marker_pickup.png
    - images/marker_destination.png

flutter_intl:
  enabled: true
